version: '3.1'

services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kafka_kicker
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: kafka_kicker

  zookeeper:
    extends:
      service: zookeeper
      file: lib/src/main/resources/docker-compose.yaml

  kafka:
    extends:
      service: broker
      file: lib/src/main/resources/docker-compose.yaml
