version: '3.1'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: insecure

  zookeeper:
    extends:
      service: zookeeper
      file: lib/src/main/resources/docker-compose.yaml

  kafka:
    extends:
      service: broker
      file: lib/src/main/resources/docker-compose.yaml
