/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ch.sonofabit.kafka.kicker.app

import ch.sonofabit.kafka.kicker.lib.Hello

class App {
    val greeting: String
        get() {
            return Hello().foo
        }
}

fun main() {
    println(App().greeting)
}
