quarkus:
  # noinspection YAMLSchemaValidation
  devservices:
    enabled: false
  datasource:
    db-kind: postgresql
  hibernate-orm:
    database:
      generation: update
  smallrye-openapi:
    servers:
      - "http://localhost:8080/"
